version: '3.3'
services:
  zookeeper:
    image: debezium/zookeeper:1.4
    container_name: zookeeper
    ports:
     - 2181:2181
  kafka:
    image: debezium/kafka:1.4
    container_name: kafka
    ports:
     - 9092:9092
    depends_on:
      - zookeeper
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka_manager
    ports:
      - 9000:9000
    depends_on:
      - kafka
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
  mysql:
    build:
      context: debezium-mysql
    container_name: mysql
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=debezium
     - MYSQL_DATABASE=inventory
     - MYSQL_PASSWORD=dbz
    volumes:
      - mysql-db-new-test:/var/lib/mysql
  connect:
    build:
      context: debezium-jdbc
    container_name: connect
    ports:
     - 8083:8083
    depends_on:
      - mysql
      - kafka
    volumes:
     - mysql-connector-new-test:/kafka/connect/kafka-connect-mysql/
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
  redshift:
    build:
      context: debezium-postgres
    container_name: redshift
    depends_on:
      - mysql
      - kafka
    ports:
      - 5432:5432
    volumes:
      - redshift-db-new-test:/usr/local/psql/data
    links:
      - kafka
      - mysql
    environment:
      - POSTGRES_DATABASE=inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=debezium
  ddlconsumerinventory:
    build:
      context: .
    container_name: dbmigration
    depends_on:
      - mysql
      - kafka
    ports:
      - 8089:8089
    links:
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVER=kafka:9092
      - GROUP_ID=mercato-test-2
      - POSTGRES_PASSWORD=debezium
  portforwarding:
    build:
      context: port-forwarding
    container_name: portforwarding
    depends_on:
      - mysql
      - kafka
      - redshift
    ports:
      - 9100:9100
    links:
      - kafka
      - mysql
      - redshift
    environment:
      - ssh_private_key=location
      - ssh_username=username
      - ssh_password=password
      - remote_bind_address=remote_addresss
      - host_path=host_path
      - database=database
      - user=user
      - password=password
      - host=host
volumes:
  mysql-db-new-test:
  mysql-connector-new-test:
  ssh-keys:
  redshift-db-new-test: